services:
  web_app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db_container
  db_container:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      .env